import pygame

SWAP_PLATEAU = pygame.USEREVENT
SWAP_MENU = pygame.USEREVENT + 1
EXIT_INTERFACE = pygame.USEREVENT + 2
SWAP_REGLE = pygame.USEREVENT + 3


PARAMETRE_SWAP_ON = pygame.USEREVENT + 4
PARAMETRE_SWAP_OFF = pygame.USEREVENT + 5

SELECTEUR_SWAP_ON = pygame.USEREVENT + 6
SELECTEUR_SWAP_OFF = pygame.USEREVENT + 7

CHANGE_MUSIC = pygame.USEREVENT + 8